In [2]:
import pandas as pd
import numpy as np
import requests
import lxml.html as lh
from bs4 import BeautifulSoup

In [3]:
usgs_all_df = pd.read_csv('C:/Users/robert.taylor/Documents/SuwData/USGS_Wells_All_df.csv',converters={'site_no': lambda x: str(x)})
usgs_all_df.drop('Unnamed: 0', axis=1,inplace=True)
usgs_all_df.head()

,agency_cd,site_no,station_nm,site_tp_cd,dec_lat_va,dec_long_va,coord_acy_cd,dec_coord_datum_cd,alt_va,alt_acy_va,...,stat_cd,ts_id,loc_web_ds,medium_grp_cd,parm_grp_cd,srs_id,access_cd,begin_date,end_date,count_nu
0,USGS,304450081333401,33D054 St. Marys GA no.2,GW,30.747458,-81.559264,1,NAD83,10.00,2.50,...,NaN,0,NaN,wat,NaN,1642461,0,1993-05-06,2007-05-21,29
1,USGS,310810081323501,"33H188 TW-26 Colonels Island, Georgia",GW,31.136341,-81.542880,1,NAD83,9.37,0.01,...,NaN,0,NaN,wat,NaN,1642461,0,1978-12-05,2014-12-10,165
2,USGS,310825081294201,"34H393 TW-17 Glynn County, GA",GW,31.140508,-81.494823,1,NAD83,6.95,0.01,...,NaN,0,NaN,wat,NaN,1642461,0,1975-10-20,2021-05-11,117
3,USGS,312251081244301,34K095,GW,31.381892,-81.411767,F,NAD83,20.00,2.50,...,NaN,0,NaN,wat,NaN,1642461,0,1973-12-03,2016-10-24,30
4,USGS,312439081273701,34K081,GW,31.411057,-81.460103,F,NAD83,31.00,1.00,...,NaN,0,NaN,wat,NaN,1642461,0,1966-12-02,1998-05-15,25

In [4]:
ufa_all_df = pd.read_csv('C:/Users/robert.taylor/Documents/SuwData/UFAWellsInsidePolygon.txt',converters={'SITEID': lambda x: str(x)})
ufa_all_df = ufa_all_df.rename(columns={'SITEID':'site_no'})
ufa_all_df.head()

,FID,OBJECTID,site_no,SITENAME,AGENCY,OBSERVATIO,LATDD,LONGDD,HORIZONTAL,TOTALDEPTH,CASEDDEPTH,COMMENTS
0,8,9,20062,ROMP TR 21-2 U FLDN AQ CHLORIDE MONITOR,SWFWMD,Well,28.853306,-82.596806,,111.0,106.0,
1,24,25,21049,HOMOSASSA 3 FLDN,SWFWMD,Well,28.764069,-82.581572,,99.0,82.0,
2,37,38,23595,ROMP 116 U FLDN AQ MONITOR,SWFWMD,Well,28.955550,-82.337067,,55.0,39.0,
3,44,45,713731,CE 76 FLDN,SWFWMD,Well,29.183853,-82.016308,,153.0,124.0,
4,51,52,23627,FERRIS PACKING COMPANY FLDN,SWFWMD,Well,28.752336,-82.296050,,400.0,200.0,

In [5]:
display(ufa_all_df)
ufa_all_df['AGENCY'].value_counts()

,FID,OBJECTID,site_no,SITENAME,AGENCY,OBSERVATIO,LATDD,LONGDD,HORIZONTAL,TOTALDEPTH,CASEDDEPTH,COMMENTS
0,8,9,20062,ROMP TR 21-2 U FLDN AQ CHLORIDE MONITOR,SWFWMD,Well,28.853306,-82.596806,,111.0,106.0,
1,24,25,21049,HOMOSASSA 3 FLDN,SWFWMD,Well,28.764069,-82.581572,,99.0,82.0,
2,37,38,23595,ROMP 116 U FLDN AQ MONITOR,SWFWMD,Well,28.955550,-82.337067,,55.0,39.0,
3,44,45,713731,CE 76 FLDN,SWFWMD,Well,29.183853,-82.016308,,153.0,124.0,
4,51,52,23627,FERRIS PACKING COMPANY FLDN,SWFWMD,Well,28.752336,-82.296050,,400.0,200.0,
...,...,...,...,...,...,...,...,...,...,...,...,...
787,1552,1553,320754081364301,33R045,USGS,Well,32.131867,-81.611779,,994.0,994.0,120FLRDL
788,1553,1554,S121717003,,SRWMD,Well,29.446110,-82.633610,,0.0,0.0,Same as 121717003
789,1554,1555,N021013001,,SRWMD,Well,30.574181,-83.274472,,0.0,0.0,
790,1558,1559,12459,FGS - SULLIVAN SINK #1,NWFWMD,Well,30.312177,-84.361841,,0.0,0.0,
791,1563,1564,W19696,FGS 3K Deep,,Well,30.475428,-84.352745,,855.0,0.0,

SJRWMD    224
SRWMD     183
ACEPD     165
USGS      105
SWFWMD     65
NWFWMD     49
            1
Name: AGENCY, dtype: int64

In [11]:
ufa_all_df.loc[ufa_all_df['site_no']=='A-0693']

,FID,OBJECTID,site_no,SITENAME,AGENCY,OBSERVATIO,LATDD,LONGDD,HORIZONTAL,TOTALDEPTH,CASEDDEPTH,COMMENTS
74,427,428,A-0693,Alachua Fairgrounds,SJRWMD,Well,29.68465,-82.286926,,440.0,192.0,

In [7]:
inter_all_wells_df = pd.merge(usgs_all_df,ufa_all_df,how='inner',on=['site_no'])
inter_all_wells_df.to_csv('C:/Users/robert.taylor/Documents/SuwData/UFA_Wells_Inter_All_df.csv')

In [8]:
display(inter_all_wells_df)

,agency_cd,site_no,station_nm,site_tp_cd,dec_lat_va,dec_long_va,coord_acy_cd,dec_coord_datum_cd,alt_va,alt_acy_va,...,OBJECTID,SITENAME,AGENCY,OBSERVATIO,LATDD,LONGDD,HORIZONTAL,TOTALDEPTH,CASEDDEPTH,COMMENTS
0,USGS,310825081294201,"34H393 TW-17 Glynn County, GA",GW,31.140508,-81.494823,1,NAD83,6.95,0.01,...,1551,34H393,USGS,Well,31.140397,-81.494850,,1153.00,723.0,120FLRDU
1,USGS,313823081154201,35M013,GW,31.639942,-81.261488,F,NAD83,16.30,1.00,...,1454,35M013,USGS,Well,31.639942,-81.261488,NAD83,553.00,0.0,120FLRDU
2,USGS,313845081361701,33M004,GW,31.648550,-81.600944,F,NAD83,60.30,1.00,...,1455,33M004,USGS,Well,31.648550,-81.600944,NAD83,870.00,0.0,120FLRDU
3,USGS,315214081235301,34N089,GW,31.870767,-81.397887,F,NAD83,16.01,1.00,...,1457,34N089,USGS,Well,31.870767,-81.397887,NAD83,789.00,0.0,120FLRDU
4,USGS,315443081185902,35P110,GW,31.911944,-81.316389,S,NAD83,9.52,5.00,...,1458,35P110,USGS,Well,31.911944,-81.316389,NAD83,441.25,0.0,120FLRDU
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,USGS,313808084093601,12M017,GW,31.635729,-84.159908,F,NAD83,225.00,5.00,...,1453,12M017,USGS,Well,31.635729,-84.159908,NAD83,181.00,0.0,120FLRDU
94,USGS,314030084060001,13M046,GW,31.675173,-84.099907,F,NAD83,212.00,5.00,...,1548,13M046,USGS,Well,31.675173,-84.099907,,105.00,105.0,120FLRDU
95,USGS,304033083310401,17D007,GW,30.676035,-83.517655,F,NAD83,212.00,5.00,...,1409,17D007,USGS,Well,30.676035,-83.517655,NAD83,180.00,0.0,120FLRDU
96,USGS,304750084332201,09E009,GW,30.797522,-84.555936,F,NAD83,300.00,5.00,...,1380,09E009,USGS,Well,307975.215000,845559.387000,,0.00,0.0,120FLRDU
97,USGS,304959083584801,14E031,GW,30.832883,-83.980092,5,NAD83,257.00,1.00,...,1411,14E031,USGS,Well,30.832970,-83.979892,NAD83,405.00,0.0,120FLRDU