In [261]:
import pandas as pd
import numpy as np
import requests
import lxml.html as lh
import urllib
import os
from bs4 import BeautifulSoup

### Inside the quotations in the box below, input the directory where you have saved the "SuwData" and this script file.

In [262]:
directory = "C:/Users/robert.taylor/Documents/"

### Enter the site type below you would like to search from: 'Stream', 'Spring', or 'Well'. The type is then translated to thir respective terms for each agency.

In [296]:
site_type = 'Well'

if site_type == 'Spring':
    srwmd_site_type = 'Spring'
    srwmd_type_df = srwmd_sites_df[srwmd_sites_df['stn_type'].str.startswith(srwmd_site_type)]
    usgs_site_type = 'SP'
    
elif site_type == 'Well':
    srwmd_site_type = 'Monitor Well'
    srwmd_type_df = srwmd_sites_df[srwmd_sites_df['stn_type'].str.startswith(srwmd_site_type)]
    usgs_site_type = 'GW'
    
elif site_type == 'Stream':
    srwmd_site_type = 'River', 'Creek', 'Surface Water'
    srwmd_type_df = srwmd_sites_df[srwmd_sites_df['stn_type'].str.startswith(tuple(srwmd_site_type))]
    usgs_site_type = 'ST'

else:
    print('Check site type.')

## EPA

### The box below reads in the pre-downloaded metadata file from the EPA's Water Quality Portal (WQP). The third line creates a new dataframe based on the search of 'MonitoringLocationTypeName'. The final line dispays a portion of the dataframe.

In [297]:
epa_sites_df = pd.read_csv(directory + 'SuwData/EPA_All_sites_Meta.csv')
epa_springs_df = epa_sites_df.loc[epa_sites_df['MonitoringLocationTypeName'] == site_type]
epa_springs_df

,Unnamed: 0,count_nu,OrganizationIdentifier,OrganizationFormalName,MonitoringLocationIdentifier,MonitoringLocationName,MonitoringLocationTypeName,MonitoringLocationDescriptionText,HUCEightDigitCode,DrainageAreaMeasure/MeasureValue,...,CountyCode,AquiferName,FormationTypeText,AquiferTypeName,ConstructionDateText,WellDepthMeasure/MeasureValue,WellDepthMeasure/MeasureUnitCode,WellHoleDepthMeasure/MeasureValue,WellHoleDepthMeasure/MeasureUnitCode,ProviderName
271,0,24,USGS-FL,USGS Florida Water Science Center,USGS-300143082565903,ROBERTS-4 W-17269,Well,NaN,3110205,NaN,...,121,Floridan aquifer system,Floridan Aquifer System,Unconfined single aquifer,19950617.0,42.6,ft,42.6,ft,NWIS
272,1,63,USGS-FL,USGS Florida Water Science Center,USGS-300200083090001,TRAWICK L3-1,Well,NaN,3110205,NaN,...,67,Surficial aquifer system,Surficial Aquifer System,NaN,19900216.0,NaN,NaN,NaN,NaN,NWIS
273,2,54,USGS-FL,USGS Florida Water Science Center,USGS-300200083090002,TRAWICK L3-2,Well,NaN,3110205,NaN,...,67,Intermediate aquifer system,Hawthorn Formation,NaN,19900216.0,NaN,NaN,NaN,NaN,NWIS
274,3,36,USGS-FL,USGS Florida Water Science Center,USGS-300200083090003,TRAWICK L3-3,Well,NaN,3110205,NaN,...,67,Surficial aquifer system,Surficial Aquifer System,NaN,19900215.0,NaN,NaN,NaN,NaN,NWIS
275,4,42,USGS-FL,USGS Florida Water Science Center,USGS-300200083090004,TRAWICK BARN WELL,Well,NaN,3110205,NaN,...,67,Floridan aquifer system,Upper Floridan Aquifer,NaN,NaN,63.0,ft,63.0,ft,NWIS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,94,21,21FLSUW,Suwannee River Water Management District (Flor...,21FLSUW-11510003,JOHN FOLKS-0DOF-0CHRISTIE TWR,Well,JOHN FOLKS-0DOF-0CHRISTIE TWR,3110201,NaN,...,47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET
366,95,23,21FLSUW,Suwannee River Water Management District (Flor...,21FLSUW-11714002,HORACE HART OLD BENTON,Well,HORACE HART OLD BENTON,3110201,NaN,...,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET
367,96,27,21FLSUW,Suwannee River Water Management District (Flor...,21FLSUW-21036001,WILLIAM LASSITER,Well,WILLIAM LASSITER,3110203,NaN,...,79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET
368,97,22,21FLSUW,Suwannee River Water Management District (Flor...,21FLSUW-21332004,JOHN FOLKS-0DOF-0ALAPAHA TOWER,Well,JOHN FOLKS-0DOF-0ALAPAHA TOWER,3110202,NaN,...,47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET
369,98,24,21FLSUW,Suwannee River Water Management District (Flor...,21FLSUW-31034003,JOHN BLALOCK,Well,JOHN BLALOCK,3110203,NaN,...,79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET

## USGS

### The box below reads in the pre-downloaded metadata file from the USGS Site Web Service. A new dataframe based on the search of 'site_tp_cd' is created. The last line dispays a portion of the dataframe.

In [298]:
usgs_sites_df = pd.read_csv(directory + 'SuwData/USGS_All_Sites_In_Basin.csv',converters={'site_no': lambda x: str(x)})
   
usgs_springs_df = usgs_sites_df.loc[usgs_sites_df['site_tp_cd'] == usgs_site_type]
usgs_springs_df

,Unnamed: 0,agency_cd,site_no,station_nm,site_tp_cd,dec_lat_va,dec_long_va,coord_acy_cd,dec_coord_datum_cd,alt_va,...,stat_cd,ts_id,loc_web_ds,medium_grp_cd,parm_grp_cd,srs_id,access_cd,begin_date,end_date,count_nu
533,4,USGS,292507082560201,A J MIMMS(121420)SR 347 SW OF CHIEFLAND,GW,29.418850,-82.933733,S,NAD83,33.0,...,NaN,0,NaN,wat,NaN,1642461,0,1986-09-17,2009-05-19,28
534,5,USGS,292507082560201,A J MIMMS(121420)SR 347 SW OF CHIEFLAND,GW,29.418850,-82.933733,S,NAD83,33.0,...,NaN,0,NaN,wat,NaN,1642461,0,1986-09-17,2009-05-19,28
535,6,USGS,292507082560201,A J MIMMS(121420)SR 347 SW OF CHIEFLAND,GW,29.418850,-82.933733,S,NAD83,33.0,...,NaN,0,NaN,wat,NaN,1642008,0,1986-09-17,2009-05-19,28
536,7,USGS,292713082493601,"H.E.MILLS NR CHIEFLAND,FL",GW,29.453852,-82.826507,S,NAD83,31.0,...,NaN,0,NaN,wat,NaN,1642461,0,1984-05-15,2009-05-19,39
537,8,USGS,292713082493601,"H.E.MILLS NR CHIEFLAND,FL",GW,29.453852,-82.826507,S,NAD83,31.0,...,NaN,0,NaN,wat,NaN,1642461,0,1984-05-15,2009-05-19,39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
810,2609,USGS,313233083502401,15L021,GW,31.538011,-83.845794,5,NAD83,382.0,...,NaN,0,NaN,wat,NaN,1642461,0,1972-01-25,2008-11-04,21
811,2610,USGS,313233083502401,15L021,GW,31.538011,-83.845794,5,NAD83,382.0,...,NaN,0,NaN,wat,NaN,1642008,0,1972-01-25,2008-11-04,21
812,3004,USGS,313950083425401,16M015,GW,31.664069,-83.714893,F,NAD83,417.0,...,NaN,0,NaN,wat,NaN,1642461,0,1994-02-24,2021-04-14,30
813,3005,USGS,313950083425401,16M015,GW,31.664069,-83.714893,F,NAD83,417.0,...,NaN,0,NaN,wat,NaN,1642461,0,1994-02-24,2021-04-14,30
814,3006,USGS,313950083425401,16M015,GW,31.664069,-83.714893,F,NAD83,417.0,...,NaN,0,NaN,wat,NaN,1642008,0,1994-02-24,2021-04-14,30

## SRWMD

### The box below reads in the pre-downloaded metadata file from SRWMD. A new dataframe based on the search of 'stn_type' is created. The last line dispays a portion of the dataframe.

In [299]:
srwmd_sites_df = pd.read_csv(directory + 'SuwData/SRWMD_All_Sites_Fixed.csv')
display(srwmd_type_df)

,Unnamed: 0,OID_,Name,FolderPath,SymbolID,AltMode,Base,Snippet,HasLabel,LabelID,Active,station_nm,dec_lat_va,dec_long_va,data_start,data_end,stn_type,county
215,215,NaN,06941689,SRWMD All Monitoring Stations/SRWMD All Data C...,7,-1,0.0,NaN,-1,1,No,LE0002 Romp 134 SWFWMD (WL) FA,29.437500,-82.457222,4/15/1983,11/9/2009,Monitor Well,Levy
396,396,NaN,N010401003,SRWMD All Monitoring Stations/SRWMD All Data C...,7,-1,0.0,NaN,-1,1,No,JOHN FOLKS-DOF-MONTICELLO,30.511352,-83.876789,3/27/2002,6/30/2005,Monitor Well,Jefferson
397,397,NaN,N010409001,SRWMD All Monitoring Stations/SRWMD All Data C...,7,-1,0.0,NaN,-1,1,No,JOSEPH BELLAMY,30.500278,-83.926111,11/1/1976,11/3/1981,Monitor Well,Jefferson
398,398,NaN,N010512001,SRWMD All Monitoring Stations/SRWMD All Data C...,7,-1,0.0,NaN,-1,1,No,MIKE PUTNAM,30.492139,-83.780686,6/21/2000,12/3/2001,Monitor Well,Jefferson
399,399,NaN,N010513001,SRWMD All Monitoring Stations/SRWMD All Data C...,7,-1,0.0,NaN,-1,1,No,L C YOUNG,30.491111,-83.783889,6/21/2000,12/3/2001,Monitor Well,Jefferson
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1559,1559,NaN,S161736001,SRWMD All Monitoring Stations/SRWMD All Data C...,7,-1,0.0,NaN,-1,1,No,WATSON TANNER,29.052778,-82.542778,12/1/1976,7/27/1981,Monitor Well,Levy
1560,1560,NaN,S161813001,SRWMD All Monitoring Stations/SRWMD All Data C...,7,-1,0.0,NaN,-1,1,No,USGS,29.087222,-82.451944,7/18/1966,5/25/2011,Monitor Well,F083
1561,1561,NaN,S171603001,SRWMD All Monitoring Stations/SRWMD All Data C...,7,-1,0.0,NaN,-1,1,No,FLORIDA POWER CORP,29.034167,-82.678333,9/15/1964,8/11/2004,Monitor Well,Levy
1562,1562,NaN,S171706001,SRWMD All Monitoring Stations/SRWMD All Data C...,7,-1,0.0,NaN,-1,1,No,USGS Yankeetown,29.026667,-82.621944,11/1/1976,5/16/1995,Monitor Well,Levy
1679,1679,NaN,N010632002,SRWMD All Monitoring Stations/SRWMD All Data C...,7,-1,0.0,NaN,-1,1,Yes,Seven Bridges UFA,30.437008,-83.740782,3/22/2017,CURRENT,Monitor Well,Jefferson

Monitor Well

# Search

### The following box requires more involvement. In time, the column names will be synchronized, but until then we need to reference the tables above to figure out what the parameter is called that we want to search for in each dataset. Currently, we are searching by name. In the searchfor variable, we type in strings for all the key words we are searching for and at this time it is case sensitive. One new dataframe is created for each datasource with the matches.

In [243]:
searchfor = ['DEVIL', 'HORNSBY', 'ICHETUCKNEE', 'Ichetucknee', 'BLUE HOLE', 'Blue Hole', 'GINNIE', 'JULY', 'Hornsby']
search_results_epa = epa_springs_df[epa_springs_df['MonitoringLocationName'].str.startswith(tuple(searchfor))]
search_results_usgs = usgs_springs_df[usgs_springs_df['station_nm'].str.startswith(tuple(searchfor))]
search_results_srwmd = srwmd_springs_df[srwmd_springs_df['station_nm'].str.startswith(tuple(searchfor))]

In [244]:
display(search_results_epa)
display(search_results_usgs)
display(search_results_srwmd)

,Unnamed: 0,count_nu,OrganizationIdentifier,OrganizationFormalName,MonitoringLocationIdentifier,MonitoringLocationName,MonitoringLocationTypeName,MonitoringLocationDescriptionText,HUCEightDigitCode,DrainageAreaMeasure/MeasureValue,...,CountyCode,AquiferName,FormationTypeText,AquiferTypeName,ConstructionDateText,WellDepthMeasure/MeasureValue,WellDepthMeasure/MeasureUnitCode,WellHoleDepthMeasure/MeasureValue,WellHoleDepthMeasure/MeasureUnitCode,ProviderName
4,4,59,USGS-FL,USGS Florida Water Science Center,USGS-02322400,GINNIE SPRING NR HIGH SPRINGS FLA,Spring,NaN,3110206,NaN,...,41,Floridan aquifer system,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NWIS
5,5,184,USGS-FL,USGS Florida Water Science Center,USGS-02322688,"BLUE HOLE SPRING NR HILDRETH, FL",Spring,NaN,3110206,NaN,...,23,Floridan aquifer system,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NWIS
11,11,23,21FLFSI_WQX,HOWARD T ODUM FLORIDA SPRINGS INSTITUTE,21FLFSI_WQX-ICH BLUE HOLE SPRING,Blue Hole Spring,Spring,NaN,3110206,NaN,...,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET
12,12,25,21FLFSI_WQX,HOWARD T ODUM FLORIDA SPRINGS INSTITUTE,21FLFSI_WQX-ICHETUCKNEE HEAD SPRING,Ichetucknee Head Spring,Spring,NaN,3110206,NaN,...,121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET
19,19,23,21FLGW_WQX,FL Dept. of Environmental Protection,21FLGW_WQX-11407,GINNIE SPRING,Spring,GINNIE SPRING,3110206,NaN,...,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET
20,20,33,21FLGW_WQX,FL Dept. of Environmental Protection,21FLGW_WQX-11418,DEVILS EYE SPRING (GILCHRIST),Spring,DEVILS EYE SPRING (GILCHRIST),3110206,NaN,...,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET
27,27,70,21FLGW_WQX,FL Dept. of Environmental Protection,21FLGW_WQX-9677,DEVIL'S EAR SPRING,Spring,DEVIL'S EAR SPRING,3110206,NaN,...,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET
29,29,33,21FLGW_WQX,FL Dept. of Environmental Protection,21FLGW_WQX-9681,HORNSBY SPRING,Spring,HORNSBY SPRING,3110206,NaN,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET
32,32,87,21FLGW_WQX,FL Dept. of Environmental Protection,21FLGW_WQX-9713,ICHETUCKNEE SPRING MAIN,Spring,ICHETUCKNEE SPRING MAIN,3110206,NaN,...,121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET
34,34,76,21FLGW_WQX,FL Dept. of Environmental Protection,21FLGW_WQX-9743,BLUE HOLE SPRING VENT,Spring,BLUE HOLE SPRING VENT,3110206,NaN,...,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET
46,46,31,21FLSUW_WQX,Suwannee River Water Management District,21FLSUW_WQX-GIN010C1,GINNIE SPRINGS,Spring,GINNIE SPRINGS,3110206,NaN,...,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET
49,49,42,21FLSUW_WQX,Suwannee River Water Management District,21FLSUW_WQX-HOR010C1,HORNSBY SPRING NR HIGH SPRINGS,Spring,HORNSBY SPRING NR HIGH SPRINGS,3110206,NaN,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET
50,50,42,21FLSUW_WQX,Suwannee River Water Management District,21FLSUW_WQX-ICH002C1,BLUE HOLE SPRING VENT,Spring,BLUE HOLE SPRING VENT,3110206,NaN,...,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET

,Unnamed: 0,agency_cd,site_no,station_nm,site_tp_cd,dec_lat_va,dec_long_va,coord_acy_cd,dec_coord_datum_cd,alt_va,...,stat_cd,ts_id,loc_web_ds,medium_grp_cd,parm_grp_cd,srs_id,access_cd,begin_date,end_date,count_nu
452,70,USGS,02322400,GINNIE SPRING NR HIGH SPRINGS FLA,SP,29.836071,-82.700120,S,NAD83,NaN,...,1.0,242605,NaN,wat,NaN,1645597,0,2018-12-14,2021-07-07,571
453,71,USGS,02322400,GINNIE SPRING NR HIGH SPRINGS FLA,SP,29.836071,-82.700120,S,NAD83,NaN,...,2.0,242604,NaN,wat,NaN,1645597,0,2018-12-14,2021-07-07,571
454,72,USGS,02322400,GINNIE SPRING NR HIGH SPRINGS FLA,SP,29.836071,-82.700120,S,NAD83,NaN,...,3.0,242602,NaN,wat,NaN,17164583,0,2018-11-09,2021-07-07,925
455,73,USGS,02322400,GINNIE SPRING NR HIGH SPRINGS FLA,SP,29.836071,-82.700120,S,NAD83,NaN,...,1.0,242608,NaN,wat,NaN,1646694,0,2018-12-14,2021-07-07,578
456,74,USGS,02322400,GINNIE SPRING NR HIGH SPRINGS FLA,SP,29.836071,-82.700120,S,NAD83,NaN,...,2.0,242607,NaN,wat,NaN,1646694,0,2018-12-14,2021-07-07,578
457,75,USGS,02322400,GINNIE SPRING NR HIGH SPRINGS FLA,SP,29.836071,-82.700120,S,NAD83,NaN,...,3.0,242609,NaN,wat,NaN,1646694,0,2018-12-14,2021-07-07,578
458,76,USGS,02322400,GINNIE SPRING NR HIGH SPRINGS FLA,SP,29.836071,-82.700120,S,NAD83,NaN,...,1.0,242612,NaN,wat,NaN,154302,0,2018-12-14,2021-07-07,460
459,77,USGS,02322400,GINNIE SPRING NR HIGH SPRINGS FLA,SP,29.836071,-82.700120,S,NAD83,NaN,...,2.0,242611,NaN,wat,NaN,154302,0,2018-12-14,2021-07-07,460
460,78,USGS,02322400,GINNIE SPRING NR HIGH SPRINGS FLA,SP,29.836071,-82.700120,S,NAD83,NaN,...,3.0,242613,NaN,wat,NaN,154302,0,2018-12-14,2021-07-07,460
461,79,USGS,02322400,GINNIE SPRING NR HIGH SPRINGS FLA,SP,29.836071,-82.700120,S,NAD83,NaN,...,1.0,242616,NaN,wat,NaN,17028275,0,2018-12-14,2021-07-07,464
462,80,USGS,02322400,GINNIE SPRING NR HIGH SPRINGS FLA,SP,29.836071,-82.700120,S,NAD83,NaN,...,2.0,242615,NaN,wat,NaN,17028275,0,2018-12-14,2021-07-07,464
463,81,USGS,02322400,GINNIE SPRING NR HIGH SPRINGS FLA,SP,29.836071,-82.700120,S,NAD83,NaN,...,3.0,242617,NaN,wat,NaN,17028275,0,2018-12-14,2021-07-07,464
464,82,USGS,02322400,GINNIE SPRING NR HIGH SPRINGS FLA,SP,29.836071,-82.700120,S,NAD83,NaN,...,1.0,260189,NaN,wat,NaN,701177,0,2018-12-14,2021-07-07,554
465,83,USGS,02322400,GINNIE SPRING NR HIGH SPRINGS FLA,SP,29.836071,-82.700120,S,NAD83,NaN,...,2.0,260192,NaN,wat,NaN,701177,0,2018-12-14,2021-07-07,554
466,84,USGS,02322400,GINNIE SPRING NR HIGH SPRINGS FLA,SP,29.836071,-82.700120,S,NAD83,NaN,...,3.0,260191,NaN,wat,NaN,701177,0,2018-12-14,2021-07-07,554
467,85,USGS,02322685,"ICHETUCKNEE HEAD SPRING NR HILDRETH, FL",SP,29.983889,-82.761944,S,NAD83,21.76,...,3.0,26587,NaN,wat,NaN,1645423,0,2002-02-07,2010-06-08,3044
468,86,USGS,02322685,"ICHETUCKNEE HEAD SPRING NR HILDRETH, FL",SP,29.983889,-82.761944,S,NAD83,21.76,...,3.0,26586,NaN,wat,NaN,17164583,0,2002-02-07,2010-06-08,2963
471,89,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,1.0,26592,NaN,wat,NaN,1645597,0,2014-07-01,2021-08-03,2435
472,90,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,2.0,26593,NaN,wat,NaN,1645597,0,2014-07-01,2021-08-03,2435
473,91,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,3.0,26594,NaN,wat,NaN,1645597,0,2014-07-01,2021-08-03,2435
474,92,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,3.0,229570,NaN,wat,NaN,1645423,0,2002-02-05,2021-08-03,6930
475,93,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,3.0,26590,NaN,wat,NaN,17164583,0,2002-02-05,2021-08-03,6742
476,94,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,1.0,26595,NaN,wat,NaN,1646694,0,2014-07-02,2021-08-03,2403
477,95,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,2.0,26596,NaN,wat,NaN,1646694,0,2014-07-02,2021-08-03,2403
478,96,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,3.0,26597,NaN,wat,NaN,1646694,0,2014-07-02,2021-08-03,2403
479,97,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,1.0,26601,NaN,wat,NaN,154302,0,2014-07-01,2021-08-02,2373
480,98,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,2.0,26602,NaN,wat,NaN,154302,0,2014-07-01,2021-08-02,2373
481,99,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,3.0,26603,NaN,wat,NaN,154302,0,2014-07-01,2021-08-02,2373
482,100,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,1.0,26598,NaN,wat,NaN,17028275,0,2014-07-02,2021-08-03,2343
483,101,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,2.0,26599,NaN,wat,NaN,17028275,0,2014-07-02,2021-08-03,2343
484,102,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,8.0,26600,NaN,wat,NaN,17028275,0,2014-07-02,2021-08-03,2343
485,103,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,3.0,26610,NaN,wat,NaN,1642503,0,2014-10-01,2021-08-03,2421
486,104,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,1.0,26604,NaN,wat,NaN,701177,0,2014-07-02,2021-08-03,2094
487,105,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,2.0,26605,NaN,wat,NaN,701177,0,2014-07-02,2021-08-03,2093
488,106,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,3.0,26606,NaN,wat,NaN,701177,0,2014-07-02,2021-08-03,2094
491,109,USGS,02322694,"DEVIL'S EYE SPRING NR HILDRETH, FL",SP,29.973333,-82.760278,S,NAD83,12.50,...,3.0,26614,NaN,wat,NaN,1645423,0,2002-02-12,2010-06-09,3040
492,110,USGS,02322694,"DEVIL'S EYE SPRING NR HILDRETH, FL",SP,29.973333,-82.760278,S,NAD83,12.50,...,3.0,26613,NaN,wat,NaN,17164583,0,2002-02-12,2010-06-09,2903
495,113,USGS,02322698,"ICHETUCKNEE R A DAMPIER'S LANDING NR HILDRETH, FL",SP,29.960278,-82.772222,S,NAD83,8.62,...,3.0,26618,NaN,wat,NaN,1645423,0,2002-02-14,2012-09-29,3751
496,114,USGS,02322698,"ICHETUCKNEE R A DAMPIER'S LANDING NR HILDRETH, FL",SP,29.960278,-82.772222,S,NAD83,8.62,...,3.0,26617,NaN,wat,NaN,17164583,0,2002-02-15,2012-09-29,3659

,Unnamed: 0,OID_,Name,FolderPath,SymbolID,AltMode,Base,Snippet,HasLabel,LabelID,Active,station_nm,dec_lat_va,dec_long_va,data_start,data_end,stn_type,county
131,131,NaN,02321970,SRWMD All Monitoring Stations/SRWMD All Data C...,3,-1,0.0,NaN,-1,1,Yes,Hornsby Springs,29.850639,-82.592194,4/19/1972,CURRENT,Spring,Alachua
151,151,NaN,02322685,SRWMD All Monitoring Stations/SRWMD All Data C...,3,-1,0.0,NaN,-1,1,Yes,Ichetucknee Head Spring,30.022543,-82.777496,7/11/1975,CURRENT,Spring,Suwannee
152,152,NaN,02322688,SRWMD All Monitoring Stations/SRWMD All Data C...,3,-1,0.0,NaN,-1,1,Yes,BLUE HOLE SPRING,29.979444,-82.758611,5/17/1946,CURRENT,Spring,Columbia
154,154,NaN,02322698,SRWMD All Monitoring Stations/SRWMD All Data C...,3,-1,0.0,NaN,-1,1,No,Ichetucknee River at Dampier's Landing,29.960389,-82.771278,8/11/1993,1/1/2015,Spring,Columbia
156,156,NaN,02322702,SRWMD All Monitoring Stations/SRWMD All Data C...,6,-1,0.0,NaN,-1,1,No,Ichetucknee River Upstream of Santa Fe Confluence,29.933804,-82.798818,12/12/2017,9/20/2018,Surface Water,Columbia
286,286,NaN,DYE010C1,SRWMD All Monitoring Stations/SRWMD All Data C...,3,-1,0.0,NaN,-1,1,No,DEVIL EYE SANTA FE RIVER,29.835114,-82.696594,11/4/1997,11/4/1997,Spring,Gilchrist

### Below, the site information for all of the search results are extracted and the unique values are printed (so that one site with multiple parameters is not repeated).

In [245]:
id_search_results_epa = search_results_epa[['OrganizationIdentifier', 'OrganizationFormalName','MonitoringLocationIdentifier', 'MonitoringLocationName','MonitoringLocationTypeName','LatitudeMeasure','LongitudeMeasure']]
id_search_results_usgs = search_results_usgs[['site_no','station_nm','dec_lat_va','dec_long_va','site_tp_cd']]
id_search_results_srwmd = search_results_srwmd[['Name','station_nm','dec_lat_va','dec_long_va']]

id_search_results_usgs.drop_duplicates(inplace=True)

valid_epa_sites = search_results_epa.MonitoringLocationIdentifier.unique()
valid_usgs_sites = search_results_usgs.site_no.unique()
valid_srwmd_sites = search_results_srwmd.Name.unique()

<ipython-input-245-3a732bbc335a>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  id_search_results_usgs.drop_duplicates(inplace=True)

### In the first box below, the site IDs for the search results are printed. There is a significant chance of overlap between the datasets which is something that should be addressed. We may want to pull all USGS water quality data from the EPA and only collect water quantity data from the USGS directly for simplicity.

### The second box below either automatically passes the list of sites to a new variable for retrieval, or if you'd rather pick and choose from the list of printed sites to avoid duplicates or for another purpose, you can type them out as seen in the comment below the epa_sites_retrieve variable.

In [246]:
print("EPA sites: " + str(valid_epa_sites))
print("USGS sites: "+str(valid_usgs_sites))
print("SRWMD sites: "+str(valid_srwmd_sites))

EPA sites: ['USGS-02322400' 'USGS-02322688' '21FLFSI_WQX-ICH BLUE HOLE SPRING'
 '21FLFSI_WQX-ICHETUCKNEE HEAD SPRING' '21FLGW_WQX-11407'
 '21FLGW_WQX-11418' '21FLGW_WQX-9677' '21FLGW_WQX-9681' '21FLGW_WQX-9713'
 '21FLGW_WQX-9743' '21FLSUW_WQX-GIN010C1' '21FLSUW_WQX-HOR010C1'
 '21FLSUW_WQX-ICH002C1']
USGS sites: ['02322400' '02322685' '02322688' '02322694' '02322698']
SRWMD sites: ['02321970' '02322685' '02322688' '02322698' '02322702' 'DYE010C1']

In [247]:
epa_sites_retrieve = valid_epa_sites
# or epa_sites_retrieve = ['USGS-02322400', 'USGS-02322688', etc...]

usgs_sites_retrieve = valid_usgs_sites

srwmd_sites_retrieve = valid_srwmd_sites

# Retrieval

### Below, type the name of the folder you'd like to create to store the data from the search as the foldername variable. It will be created within the 'SuwData' folder. 

### Note: This command will fail if the folder already exists.

In [248]:
foldername = 'FolderName'
datafolderdir = str(directory + 'SuwData/' + foldername + '/')
datafolder = os.mkdir(datafolderdir)

FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:/Users/robert.taylor/Documents/SuwData/FolderName/'

## EPA Retrieval

### The following lines of code read in the EPA data and pick out the data that applis to the search results. It combines the data with some important metadata and saves the data to a csv with the assigned in the fourth line. I use a generic name because the data is being saved to the unique folder created earlier.

In [ ]:
wqp_n_results = pd.read_csv(directory + 'SuwData/EPA/EPA_All_Results.csv', converters={'USGSPCode': lambda x: str(x)})
epa_search_data = wqp_n_results.loc[wqp_n_results_spring['MonitoringLocationIdentifier'].str.startswith(tuple(epa_sites_retrieve))]
epa_search_data = id_search_results_epa.merge(epa_search_data,on='MonitoringLocationIdentifier')
epa_search_data.to_csv(str(datafolderdir + 'epa_search_result_data.csv'))

## USGS Retrieval

### The process for pulling USGS data is a bit more complicated. Here, I generated a URL to download data based on site name. It is only pulling data from sites that measure at least one of six physical parameters (listed in table below).

In [ ]:
parm_codes=pd.read_csv(directory + 'SuwData/USGS_All_Parameter_Codes.csv', converters={'parm_cd':lambda x: str(x)})

parms = ['00010', '00060', '62611', '72019', '00065', '63160']
parm_codes_used = parm_codes.loc[parm_codes['parm_cd'].str.startswith(tuple(parms))]
display(parm_codes_used)

### The box below pulls the data using a For-loop where it places each site number into the url, reads the html table, and stores the data in a Python dictionary. The dictionary is accessed using "keys" which are automatically stored as "site_no_xxxxxxxx".

In [ ]:
count = 0
usgs_dict={}
    

for i in range(len(usgs_sites_retrieve)):
    usgs_site_no = usgs_sites_retrieve[i]
    url = 'https://waterdata.usgs.gov/nwis/dv?referred_module=sw&search_site_no='+usgs_site_no+'&search_site_no_match_type=exact&site_tp_cd=ST&site_tp_cd=SP&site_tp_cd=GW&dv_count_nu=20&index_pmcode_00061=1&index_pmcode_00065=1&index_pmcode_62611=1&index_pmcode_63160=1&index_pmcode_72019=1&index_pmcode_00010=1&group_key=NONE&sitefile_output_format=html_table&column_name=agency_cd&column_name=site_no&column_name=station_nm&column_name=site_tp_cd&column_name=dec_lat_va&column_name=dec_long_va&column_name=huc_cd&range_selection=date_range&begin_date=1980-01-01&end_date=2021-08-18&format=rdb&date_format=YYYY-MM-DD&rdb_compression=value&list_of_search_criteria=search_site_no%2Csite_tp_cd%2Crealtime_parameter_selection'
    page = urllib.request.urlopen(url)
    skiplines = str(page.read())
    skiprow = skiplines.count('#')
    usgs_site_data = pd.read_csv(url,sep='\t',skiprows=skiprow)
    usgs_site_data.drop([0],axis=0,inplace=True)
    
            
            
    
    usgs_dict['site_no_'+str(usgs_site_no)] = usgs_site_data
    count += 1

### Below is an example of one site that was pulled.

In [ ]:
usgs_dict['site_no_'+usgs_site_no]

### Due to the USGS system of reporting data that I am referencing, the column headers were abstract and problematic. Each parameter has a unique identifier, there is a different identifier if it is mena, max, or min, and there is a separate column for reporting data quality / status. To combat this I used regex to extract the relevant information and title the columns automatically. This also must be performed in a loop.

In [ ]:
header = usgs_dict['site_no_'+usgs_site_no].columns.values.tolist()
header = pd.DataFrame(header,columns=['cols'])
header = header.cols.str.extract(r'^\w\w\w\w\w_([^_]+)_(.+)',expand=False)


keys = list(usgs_dict)
print('Keys: ' + str(keys))

hdr = {}

for x in range(len(usgs_dict)):
    
    header = usgs_dict[keys[x]].columns.values.tolist()
    header = pd.DataFrame(header,columns=['cols'])
    header = header.cols.str.extract(r'^\w{3,8}_([^_]+)_(.+)',expand=False)
    
    for i in range(header.shape[0]):
        for j in range(header.shape[1]):
            if header.iloc[i,j] == '00001':
                header.iloc[i,j] = ', Max value'
            elif header.iloc[i,j] == '00002':
                header.iloc[i,j] = ', Min value'
            elif header.iloc[i,j] == '00003':
                header.iloc[i,j] = ', Mean value'
            elif header.iloc[i,j] == '00001_cd':
                header.iloc[i,j] = ' Data status / quality'
            elif header.iloc[i,j] == '00002_cd':
                header.iloc[i,j] = ' Data status / quality'
            elif header.iloc[i,j] == '00003_cd':
                header.iloc[i,j] = ' Data status / quality'
            elif pd.isna(header.iloc[i,j]) is False:
                header.iloc[i,j] = parm_codes.loc[parm_codes['parm_cd'] == str(header.iloc[i,j])]['parm_desc'].values
    
    hdr[keys[x]] = header
        

for i in range(len(usgs_dict)):
    hdr[keys[i]]['header'] = hdr[keys[i]][0].astype(str) + hdr[keys[i]][1].astype(str)
    hdr[keys[i]] = hdr[keys[i]]['header']
    hdr[keys[i]].iloc[0] = 'agency_cd'
    hdr[keys[i]].iloc[1] = 'site_no'
    hdr[keys[i]].iloc[2] = 'datetime'
    

#display(hdr[keys[0]].values.tolist())



header_usgs = {}



for i in range(len(usgs_dict)):
    header_usgs[keys[i]] = usgs_dict[keys[i]].columns.values.tolist()
    usgs_dict[keys[i]].columns = hdr[keys[i]].values

### Shown below is an example of the replaced column headers and associated data.

In [ ]:
display(usgs_dict[keys[0]])

### The following box saves each site's data as a csv in the previously designated folder.

In [ ]:
for i in range(len(usgs_dict)):
    usgs_dict[keys[i]] = id_search_results_usgs.merge(usgs_dict[keys[i]],on='site_no')
    #usgs_dict[keys[i]] = usgs_dict[keys[i]].merge(id_search_results_usgs,on='site_no')
    usgs_dict[keys[i]].to_csv(datafolderdir+'/USGS_'+keys[i]+'_data.csv')