In [14]:
import pandas as pd
import numpy as np
import requests
import lxml.html as lh
from bs4 import BeautifulSoup

In [18]:
sjrwmd_sites_df = pd.read_csv('C:/Users/robert.taylor/Documents/ArcGIS/SJRWMD_UFA_Wells_Polygon.txt',converters={'HYDRON_NUMBER': lambda x: str(x)})
sjrwmd_sites_df.head()
display(sjrwmd_sites_df)

,OBJECTID,STN_ID,LAT_NO,LONG_NO,LATITUDE,LONGITUDE,SHORT_NAME,LONG_NAME,HYDRON_NUMBER,MAJOR_SW_BASIN,MINOR_SW_BASIN,COUNTY,STATION_TYPE,DATA_TYPE,GROUND_WATER_TYPE,WEB_CD,WEB_TEXT,EVNT_TP_NM,STTS_CD,TELEM_TP_CD
0,382,58039,294104.750,821712.940,29.684653,-82.286928,A-0693,A-0693 Alachua County Fairgrounds at Gainesvil...,00260030,Orange Creek,Ocklawaha River,Alachua,Well,Water Level (WL),FAS - Upper Floridan aquifer,1.0,,Water Level (WL),1,C
1,439,57609,291050.770,811431.320,29.180769,-81.242033,V-0790,V-0790 Dan Ford Rd South at Ormond Beach (WL) FA,01051575,Crescent Lake,Lower St. Johns River,Volusia,Well,Water Level (WL),FAS - Upper Floridan aquifer,1.0,,Water Level (WL),0,NaN
2,440,57611,291016.000,811431.320,29.171111,-81.242033,V-0791,V-0791 Dan Ford Rd South at Ormond Beach (WL) FA,01051576,Crescent Lake,Lower St. Johns River,Volusia,Well,Water Level (WL),FAS - Upper Floridan aquifer,1.0,,Water Level (WL),0,NaN
3,543,57434,293951.270,814139.470,29.664242,-81.694297,P-0123,P-0123 District Head Quarters (WL) FA,02101109,Etonia Creek,Lower St. Johns River,Putnam,Well,Water Level (WL),FAS - Upper Floridan aquifer,1.0,,Water Level (WL),1,R
4,545,57032,294127.260,812911.850,29.690906,-81.486625,SJ0263,SJ0263 Dick Reid Farm (WL) FA,02161132,Deep Creek Unit,Lower St. Johns River,St. Johns,Well,Water Level (WL),FAS - Upper Floridan aquifer,99.0,,Water Level (WL),0,R
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352,2688,58063,291747.100,815626.860,29.296417,-81.940794,M-0025,M-0025 CE54 Gores Landing (WL) FA,71091597,Rodman Reservoir Unit,Ocklawaha River,Marion,Well,Water Level (WL),FAS - Upper Floridan aquifer,1.0,,Water Level (WL),1,R
353,2689,56668,291048.850,811442.260,29.180236,-81.245072,V-0700,V-0700 Dan Ford Rd North at Ormond Beach (WL) FA,71101334,Crescent Lake,Lower St. Johns River,Volusia,Well,Water Level (WL),FAS - Upper Floridan aquifer,1.0,,Water Level (WL),0,NaN
354,2690,58066,291135.954,820156.084,29.193321,-82.032246,M-0026,M-0026 CE47 at Silver Springs (WL) FA,71141347,Marshall Swamp Unit,Ocklawaha River,Marion,Well,Water Level (WL),FAS - Upper Floridan aquifer,1.0,,Water Level (WL),1,C
355,2692,56834,291345.600,811557.390,29.229333,-81.265942,V-0090,V-0090 Union Camp (WL) FA,71241599,Crescent Lake,Lower St. Johns River,Volusia,Well,Water Level (WL),FAS - Upper Floridan aquifer,1.0,,Water Level (WL),0,R
356,2693,57731,303541.464,814948.344,30.594851,-81.830096,N-0220,N-0220 Callahan Fair Ground (WL) FA,71341600,NaN,Nassau River,Nassau,Well,Water Level (WL),FAS - Upper Floridan aquifer,1.0,,Water Level (WL),1,C

In [20]:
site_no = '71341600'
sjrwmd_site_data = 'http://webapub.sjrwmd.com/agws10/hdsnew/data.aspx?tp=3&stn='+site_no+'_NAVD1988_POR'
sjrwmd_req = requests.get(sjrwmd_site_data)

sjrwmd_data_table = pd.read_html(sjrwmd_req.text, match='2', header=0, skiprows=0,converters={'Station Number': lambda x: str(x)})

sjrwmd_data_df = sjrwmd_data_table[1]
sjrwmd_data_df.head()

,Station Number,Type,Source Variable,Output Variable,Date,Time,Water Level (ft NAVD88),Quality Code,Source,Quality Description,Unnamed: 10
0,71341600,Manual Measurement,227.14,227.0,04/12/1995,11:15:00,42.08,2.0,03A,Good quality edited data,NaN
1,71341600,Manual Measurement,227.14,227.0,06/22/1995,10:05:00,38.71,2.0,03A,Good quality edited data,NaN
2,71341600,Manual Measurement,227.14,227.0,03/14/1996,14:30:00,39.71,2.0,03A,Good quality edited data,NaN
3,71341600,Daily Mean Computed From Continuous Data,227.10,227.0,03/15/1996,00:00:00,39.84,2.0,01A,Good quality edited data,NaN
4,71341600,Daily Mean Computed From Continuous Data,227.10,227.0,03/16/1996,00:00:00,39.88,2.0,01A,Good quality edited data,NaN

In [21]:
sjrwmd_data_df.drop('Unnamed: 10', axis=1, inplace=True)

In [22]:
sjrwmd_data_df.head()

,Station Number,Type,Source Variable,Output Variable,Date,Time,Water Level (ft NAVD88),Quality Code,Source,Quality Description
0,71341600,Manual Measurement,227.14,227.0,04/12/1995,11:15:00,42.08,2.0,03A,Good quality edited data
1,71341600,Manual Measurement,227.14,227.0,06/22/1995,10:05:00,38.71,2.0,03A,Good quality edited data
2,71341600,Manual Measurement,227.14,227.0,03/14/1996,14:30:00,39.71,2.0,03A,Good quality edited data
3,71341600,Daily Mean Computed From Continuous Data,227.10,227.0,03/15/1996,00:00:00,39.84,2.0,01A,Good quality edited data
4,71341600,Daily Mean Computed From Continuous Data,227.10,227.0,03/16/1996,00:00:00,39.88,2.0,01A,Good quality edited data

In [24]:
len(sjrwmd_data_df)

8290