In [86]:
import pandas as pd
import numpy as np
import requests
import lxml.html as lh
import urllib
from bs4 import BeautifulSoup

## EPA

In [87]:
epa_sites_df = pd.read_csv('C:/Users/robert.taylor/Documents/SuwData/EPA_All_sites_Meta.csv')
epa_springs_df = epa_sites_df.loc[epa_sites_df['MonitoringLocationTypeName'] == 'Spring']
epa_springs_df

,Unnamed: 0,count_nu,OrganizationIdentifier,OrganizationFormalName,MonitoringLocationIdentifier,MonitoringLocationName,MonitoringLocationTypeName,MonitoringLocationDescriptionText,HUCEightDigitCode,DrainageAreaMeasure/MeasureValue,...,CountyCode,AquiferName,FormationTypeText,AquiferTypeName,ConstructionDateText,WellDepthMeasure/MeasureValue,WellDepthMeasure/MeasureUnitCode,WellHoleDepthMeasure/MeasureValue,WellHoleDepthMeasure/MeasureUnitCode,ProviderName
0,0,174,USGS-FL,USGS Florida Water Science Center,USGS-02319302,"MADISON BLUE SPRING NR BLUE SPRINGS, FL",Spring,NaN,3110203,NaN,...,79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NWIS
1,1,94,USGS-FL,USGS Florida Water Science Center,USGS-02319520,"FALMOUTH SPRING AT FALMOUTH, FL",Spring,NaN,3110205,NaN,...,121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NWIS
2,2,147,USGS-FL,USGS Florida Water Science Center,USGS-02319950,"BLUE SPRINGS NEAR DELL,FL",Spring,NaN,3110205,NaN,...,67,Floridan aquifer system,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NWIS
3,3,149,USGS-FL,USGS Florida Water Science Center,USGS-02320250,TROY SPRING NEAR BRANFORD FLA,Spring,NaN,3110205,NaN,...,67,NaN,Ocala Limestone,NaN,NaN,NaN,NaN,NaN,NaN,NWIS
4,4,59,USGS-FL,USGS Florida Water Science Center,USGS-02322400,GINNIE SPRING NR HIGH SPRINGS FLA,Spring,NaN,3110206,NaN,...,41,Floridan aquifer system,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NWIS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,61,26,21FLSUW_WQX,Suwannee River Water Management District,21FLSUW_WQX-SSS010C1,SUWANNEE SPRINGS,Spring,SUWANNEE SPRINGS,3110201,NaN,...,121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET
62,62,37,21FLSUW_WQX,Suwannee River Water Management District,21FLSUW_WQX-SUW718971,UN-NAMED SPRING,Spring,UN-NAMED SPRING,3110205,NaN,...,121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET
63,63,37,21FLSUW_WQX,Suwannee River Water Management District,21FLSUW_WQX-TEL010C1,TELFORD SPRINGS,Spring,TELFORD SPRINGS,3110205,NaN,...,121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET
64,64,47,21FLSUW_WQX,Suwannee River Water Management District,21FLSUW_WQX-TRY010C1,TROY SPRINGS,Spring,TROY SPRINGS,3110205,NaN,...,67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET
65,65,23,21FLTLHR_WQX,FDEP TALLAHASSEE REGIONAL OPERATIONS CENTER,21FLTLHR_WQX-G1TLHR0027,Ellaville Spring,Spring,NaN,3110205,NaN,...,121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET

## USGS

In [88]:
usgs_sites_df = pd.read_csv('C:/Users/robert.taylor/Documents/SuwData/USGS_All_Sites_In_Basin.csv',converters={'site_no': lambda x: str(x)})
usgs_springs_df = usgs_sites_df.loc[usgs_sites_df['site_tp_cd'] == 'SP']
usgs_springs_df

,Unnamed: 0,agency_cd,site_no,station_nm,site_tp_cd,dec_lat_va,dec_long_va,coord_acy_cd,dec_coord_datum_cd,alt_va,...,stat_cd,ts_id,loc_web_ds,medium_grp_cd,parm_grp_cd,srs_id,access_cd,begin_date,end_date,count_nu
383,1,USGS,02315620,"HOLTON SPRINGS NEAR FT. UNION,FL",SP,30.437718,-83.057358,S,NAD83,NaN,...,3.0,175008,NaN,wat,NaN,1645423,0,2015-06-18,2016-09-29,470
384,2,USGS,02315620,"HOLTON SPRINGS NEAR FT. UNION,FL",SP,30.437718,-83.057358,S,NAD83,NaN,...,3.0,26399,NaN,wat,NaN,17164583,0,2015-06-18,2016-09-29,470
385,3,USGS,02319302,"MADISON BLUE SPRING NR BLUE SPRINGS, FL",SP,30.480491,-83.244310,F,NAD83,48.0,...,1.0,222461,NaN,wat,NaN,1645597,0,2014-07-09,2021-08-03,2003
386,4,USGS,02319302,"MADISON BLUE SPRING NR BLUE SPRINGS, FL",SP,30.480491,-83.244310,F,NAD83,48.0,...,2.0,222463,NaN,wat,NaN,1645597,0,2014-07-09,2021-08-03,2003
387,5,USGS,02319302,"MADISON BLUE SPRING NR BLUE SPRINGS, FL",SP,30.480491,-83.244310,F,NAD83,48.0,...,3.0,172070,NaN,wat,NaN,1645597,0,2014-07-09,2021-08-03,2003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
528,146,USGS,02323566,MANATEE SPRING NR CHIEFLAND FLA,SP,29.489681,-82.976791,S,NAD83,NaN,...,8.0,173563,NaN,wat,NaN,17028275,0,2014-07-02,2021-08-03,2263
529,147,USGS,02323566,MANATEE SPRING NR CHIEFLAND FLA,SP,29.489681,-82.976791,S,NAD83,NaN,...,3.0,172501,NaN,wat,NaN,1642503,0,2014-10-01,2021-08-03,2472
530,148,USGS,02323566,MANATEE SPRING NR CHIEFLAND FLA,SP,29.489681,-82.976791,S,NAD83,NaN,...,1.0,172498,NaN,wat,NaN,701177,0,2014-07-02,2021-08-03,2222
531,149,USGS,02323566,MANATEE SPRING NR CHIEFLAND FLA,SP,29.489681,-82.976791,S,NAD83,NaN,...,2.0,172500,NaN,wat,NaN,701177,0,2014-07-02,2021-08-03,2223
532,150,USGS,02323566,MANATEE SPRING NR CHIEFLAND FLA,SP,29.489681,-82.976791,S,NAD83,NaN,...,3.0,172499,NaN,wat,NaN,701177,0,2014-07-02,2021-08-03,2222

## SRWMD

In [89]:
srwmd_sites_df = pd.read_csv('C:/Users/robert.taylor/Documents/SuwData/SRWMD_All_Sites_Fixed.csv')
srwmd_springs_df = srwmd_sites_df.loc[srwmd_sites_df['stn_type'] == 'Spring']
srwmd_springs_df

,Unnamed: 0,OID_,Name,FolderPath,SymbolID,AltMode,Base,Snippet,HasLabel,LabelID,Active,station_nm,dec_lat_va,dec_long_va,data_start,data_end,stn_type,county
41,41,NaN,02313450,SRWMD All Monitoring Stations/SRWMD All Data C...,3,-1,0.0,NaN,-1,1,Yes,Levy Blue Spring near Bronson,29.450556,-82.699167,10/16/1997,CURRENT,Spring,Levy
43,43,NaN,02313600,SRWMD All Monitoring Stations/SRWMD All Data C...,3,-1,0.0,NaN,-1,1,Yes,Wekiva Springs near Gulf Hammock,29.280278,-82.656389,10/1/1997,1/31/2019,Spring,Levy
55,55,NaN,02315503,SRWMD All Monitoring Stations/SRWMD All Data C...,3,-1,0.0,NaN,-1,1,Yes,White Sulfur Springs,30.333056,-82.761111,2/13/1907,CURRENT,Spring,Columbia
56,56,NaN,02315512,SRWMD All Monitoring Stations/SRWMD All Data C...,3,-1,0.0,NaN,-1,1,No,Blue Sink near White Springs,30.335556,-82.808611,5/15/1998,2/14/2018,Spring,Suwannee
62,62,NaN,02315600,SRWMD All Monitoring Stations/SRWMD All Data C...,3,-1,0.0,NaN,-1,1,Yes,SUWANNEE SPRINGS,30.393889,-82.933333,5/17/1906,1/16/2019,Spring,Suwannee
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1666,1666,NaN,WAS109C1,SRWMD All Monitoring Stations/SRWMD All Data C...,3,-1,0.0,NaN,-1,1,No,THOMAS SPRING ON THE WACISSA RIVER,30.339706,-83.992338,3/19/1999,3/19/1999,Spring,Jefferson
1667,1667,NaN,WCR010C1,SRWMD All Monitoring Stations/SRWMD All Data C...,3,-1,0.0,NaN,-1,1,No,WOODS CREEK RISE,30.123992,-83.624289,8/7/1999,4/25/2018,Spring,Taylor
1674,1674,NaN,WEK100C1,SRWMD All Monitoring Stations/SRWMD All Data C...,3,-1,0.0,NaN,-1,1,No,Wekiva River Below Confluence with Little Wekiva,29.222625,-82.737789,11/8/2006,9/28/2016,Spring,Levy
1675,1675,NaN,WIL010C1,SRWMD All Monitoring Stations/SRWMD All Data C...,3,-1,0.0,NaN,-1,1,Yes,WILSON SPRING,29.899908,-82.758486,9/28/1997,2/27/2019,Spring,Columbia
1677,1677,NaN,WLK010C1,SRWMD All Monitoring Stations/SRWMD All Data C...,3,-1,0.0,NaN,-1,1,No,WALKER SPRING,30.280876,-83.853573,11/14/2003,11/14/2003,Spring,Jefferson

# Search

In [90]:
searchfor = ['DEVIL', 'HORNSBY', 'ICHETUCKNEE', 'Ichetucknee', 'Blue Hole', 'BLUE HOLE', 'GINNIE', 'JULY', 'Hornsby']

search_results_epa = epa_springs_df[epa_springs_df['MonitoringLocationName'].str.startswith(tuple(searchfor))]
search_results_usgs = usgs_springs_df[usgs_springs_df['station_nm'].str.startswith(tuple(searchfor))]
search_results_srwmd = srwmd_springs_df[srwmd_springs_df['station_nm'].str.startswith(tuple(searchfor))]

In [104]:
display(search_results_epa)
display(search_results_usgs)
display(search_results_srwmd)

,Unnamed: 0,count_nu,OrganizationIdentifier,OrganizationFormalName,MonitoringLocationIdentifier,MonitoringLocationName,MonitoringLocationTypeName,MonitoringLocationDescriptionText,HUCEightDigitCode,DrainageAreaMeasure/MeasureValue,...,CountyCode,AquiferName,FormationTypeText,AquiferTypeName,ConstructionDateText,WellDepthMeasure/MeasureValue,WellDepthMeasure/MeasureUnitCode,WellHoleDepthMeasure/MeasureValue,WellHoleDepthMeasure/MeasureUnitCode,ProviderName
4,4,59,USGS-FL,USGS Florida Water Science Center,USGS-02322400,GINNIE SPRING NR HIGH SPRINGS FLA,Spring,NaN,3110206,NaN,...,41,Floridan aquifer system,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NWIS
5,5,184,USGS-FL,USGS Florida Water Science Center,USGS-02322688,"BLUE HOLE SPRING NR HILDRETH, FL",Spring,NaN,3110206,NaN,...,23,Floridan aquifer system,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NWIS
11,11,23,21FLFSI_WQX,HOWARD T ODUM FLORIDA SPRINGS INSTITUTE,21FLFSI_WQX-ICH BLUE HOLE SPRING,Blue Hole Spring,Spring,NaN,3110206,NaN,...,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET
12,12,25,21FLFSI_WQX,HOWARD T ODUM FLORIDA SPRINGS INSTITUTE,21FLFSI_WQX-ICHETUCKNEE HEAD SPRING,Ichetucknee Head Spring,Spring,NaN,3110206,NaN,...,121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET
19,19,23,21FLGW_WQX,FL Dept. of Environmental Protection,21FLGW_WQX-11407,GINNIE SPRING,Spring,GINNIE SPRING,3110206,NaN,...,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET
20,20,33,21FLGW_WQX,FL Dept. of Environmental Protection,21FLGW_WQX-11418,DEVILS EYE SPRING (GILCHRIST),Spring,DEVILS EYE SPRING (GILCHRIST),3110206,NaN,...,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET
27,27,70,21FLGW_WQX,FL Dept. of Environmental Protection,21FLGW_WQX-9677,DEVIL'S EAR SPRING,Spring,DEVIL'S EAR SPRING,3110206,NaN,...,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET
29,29,33,21FLGW_WQX,FL Dept. of Environmental Protection,21FLGW_WQX-9681,HORNSBY SPRING,Spring,HORNSBY SPRING,3110206,NaN,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET
32,32,87,21FLGW_WQX,FL Dept. of Environmental Protection,21FLGW_WQX-9713,ICHETUCKNEE SPRING MAIN,Spring,ICHETUCKNEE SPRING MAIN,3110206,NaN,...,121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET
34,34,76,21FLGW_WQX,FL Dept. of Environmental Protection,21FLGW_WQX-9743,BLUE HOLE SPRING VENT,Spring,BLUE HOLE SPRING VENT,3110206,NaN,...,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET
46,46,31,21FLSUW_WQX,Suwannee River Water Management District,21FLSUW_WQX-GIN010C1,GINNIE SPRINGS,Spring,GINNIE SPRINGS,3110206,NaN,...,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET
49,49,42,21FLSUW_WQX,Suwannee River Water Management District,21FLSUW_WQX-HOR010C1,HORNSBY SPRING NR HIGH SPRINGS,Spring,HORNSBY SPRING NR HIGH SPRINGS,3110206,NaN,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET
50,50,42,21FLSUW_WQX,Suwannee River Water Management District,21FLSUW_WQX-ICH002C1,BLUE HOLE SPRING VENT,Spring,BLUE HOLE SPRING VENT,3110206,NaN,...,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET

,Unnamed: 0,agency_cd,site_no,station_nm,site_tp_cd,dec_lat_va,dec_long_va,coord_acy_cd,dec_coord_datum_cd,alt_va,...,stat_cd,ts_id,loc_web_ds,medium_grp_cd,parm_grp_cd,srs_id,access_cd,begin_date,end_date,count_nu
452,70,USGS,02322400,GINNIE SPRING NR HIGH SPRINGS FLA,SP,29.836071,-82.700120,S,NAD83,NaN,...,1.0,242605,NaN,wat,NaN,1645597,0,2018-12-14,2021-07-07,571
453,71,USGS,02322400,GINNIE SPRING NR HIGH SPRINGS FLA,SP,29.836071,-82.700120,S,NAD83,NaN,...,2.0,242604,NaN,wat,NaN,1645597,0,2018-12-14,2021-07-07,571
454,72,USGS,02322400,GINNIE SPRING NR HIGH SPRINGS FLA,SP,29.836071,-82.700120,S,NAD83,NaN,...,3.0,242602,NaN,wat,NaN,17164583,0,2018-11-09,2021-07-07,925
455,73,USGS,02322400,GINNIE SPRING NR HIGH SPRINGS FLA,SP,29.836071,-82.700120,S,NAD83,NaN,...,1.0,242608,NaN,wat,NaN,1646694,0,2018-12-14,2021-07-07,578
456,74,USGS,02322400,GINNIE SPRING NR HIGH SPRINGS FLA,SP,29.836071,-82.700120,S,NAD83,NaN,...,2.0,242607,NaN,wat,NaN,1646694,0,2018-12-14,2021-07-07,578
457,75,USGS,02322400,GINNIE SPRING NR HIGH SPRINGS FLA,SP,29.836071,-82.700120,S,NAD83,NaN,...,3.0,242609,NaN,wat,NaN,1646694,0,2018-12-14,2021-07-07,578
458,76,USGS,02322400,GINNIE SPRING NR HIGH SPRINGS FLA,SP,29.836071,-82.700120,S,NAD83,NaN,...,1.0,242612,NaN,wat,NaN,154302,0,2018-12-14,2021-07-07,460
459,77,USGS,02322400,GINNIE SPRING NR HIGH SPRINGS FLA,SP,29.836071,-82.700120,S,NAD83,NaN,...,2.0,242611,NaN,wat,NaN,154302,0,2018-12-14,2021-07-07,460
460,78,USGS,02322400,GINNIE SPRING NR HIGH SPRINGS FLA,SP,29.836071,-82.700120,S,NAD83,NaN,...,3.0,242613,NaN,wat,NaN,154302,0,2018-12-14,2021-07-07,460
461,79,USGS,02322400,GINNIE SPRING NR HIGH SPRINGS FLA,SP,29.836071,-82.700120,S,NAD83,NaN,...,1.0,242616,NaN,wat,NaN,17028275,0,2018-12-14,2021-07-07,464
462,80,USGS,02322400,GINNIE SPRING NR HIGH SPRINGS FLA,SP,29.836071,-82.700120,S,NAD83,NaN,...,2.0,242615,NaN,wat,NaN,17028275,0,2018-12-14,2021-07-07,464
463,81,USGS,02322400,GINNIE SPRING NR HIGH SPRINGS FLA,SP,29.836071,-82.700120,S,NAD83,NaN,...,3.0,242617,NaN,wat,NaN,17028275,0,2018-12-14,2021-07-07,464
464,82,USGS,02322400,GINNIE SPRING NR HIGH SPRINGS FLA,SP,29.836071,-82.700120,S,NAD83,NaN,...,1.0,260189,NaN,wat,NaN,701177,0,2018-12-14,2021-07-07,554
465,83,USGS,02322400,GINNIE SPRING NR HIGH SPRINGS FLA,SP,29.836071,-82.700120,S,NAD83,NaN,...,2.0,260192,NaN,wat,NaN,701177,0,2018-12-14,2021-07-07,554
466,84,USGS,02322400,GINNIE SPRING NR HIGH SPRINGS FLA,SP,29.836071,-82.700120,S,NAD83,NaN,...,3.0,260191,NaN,wat,NaN,701177,0,2018-12-14,2021-07-07,554
467,85,USGS,02322685,"ICHETUCKNEE HEAD SPRING NR HILDRETH, FL",SP,29.983889,-82.761944,S,NAD83,21.76,...,3.0,26587,NaN,wat,NaN,1645423,0,2002-02-07,2010-06-08,3044
468,86,USGS,02322685,"ICHETUCKNEE HEAD SPRING NR HILDRETH, FL",SP,29.983889,-82.761944,S,NAD83,21.76,...,3.0,26586,NaN,wat,NaN,17164583,0,2002-02-07,2010-06-08,2963
471,89,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,1.0,26592,NaN,wat,NaN,1645597,0,2014-07-01,2021-08-03,2435
472,90,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,2.0,26593,NaN,wat,NaN,1645597,0,2014-07-01,2021-08-03,2435
473,91,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,3.0,26594,NaN,wat,NaN,1645597,0,2014-07-01,2021-08-03,2435
474,92,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,3.0,229570,NaN,wat,NaN,1645423,0,2002-02-05,2021-08-03,6930
475,93,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,3.0,26590,NaN,wat,NaN,17164583,0,2002-02-05,2021-08-03,6742
476,94,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,1.0,26595,NaN,wat,NaN,1646694,0,2014-07-02,2021-08-03,2403
477,95,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,2.0,26596,NaN,wat,NaN,1646694,0,2014-07-02,2021-08-03,2403
478,96,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,3.0,26597,NaN,wat,NaN,1646694,0,2014-07-02,2021-08-03,2403
479,97,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,1.0,26601,NaN,wat,NaN,154302,0,2014-07-01,2021-08-02,2373
480,98,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,2.0,26602,NaN,wat,NaN,154302,0,2014-07-01,2021-08-02,2373
481,99,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,3.0,26603,NaN,wat,NaN,154302,0,2014-07-01,2021-08-02,2373
482,100,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,1.0,26598,NaN,wat,NaN,17028275,0,2014-07-02,2021-08-03,2343
483,101,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,2.0,26599,NaN,wat,NaN,17028275,0,2014-07-02,2021-08-03,2343
484,102,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,8.0,26600,NaN,wat,NaN,17028275,0,2014-07-02,2021-08-03,2343
485,103,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,3.0,26610,NaN,wat,NaN,1642503,0,2014-10-01,2021-08-03,2421
486,104,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,1.0,26604,NaN,wat,NaN,701177,0,2014-07-02,2021-08-03,2094
487,105,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,2.0,26605,NaN,wat,NaN,701177,0,2014-07-02,2021-08-03,2093
488,106,USGS,02322688,"BLUE HOLE SPRING NR HILDRETH, FL",SP,29.979955,-82.758457,S,NAD83,20.31,...,3.0,26606,NaN,wat,NaN,701177,0,2014-07-02,2021-08-03,2094
491,109,USGS,02322694,"DEVIL'S EYE SPRING NR HILDRETH, FL",SP,29.973333,-82.760278,S,NAD83,12.50,...,3.0,26614,NaN,wat,NaN,1645423,0,2002-02-12,2010-06-09,3040
492,110,USGS,02322694,"DEVIL'S EYE SPRING NR HILDRETH, FL",SP,29.973333,-82.760278,S,NAD83,12.50,...,3.0,26613,NaN,wat,NaN,17164583,0,2002-02-12,2010-06-09,2903
495,113,USGS,02322698,"ICHETUCKNEE R A DAMPIER'S LANDING NR HILDRETH, FL",SP,29.960278,-82.772222,S,NAD83,8.62,...,3.0,26618,NaN,wat,NaN,1645423,0,2002-02-14,2012-09-29,3751
496,114,USGS,02322698,"ICHETUCKNEE R A DAMPIER'S LANDING NR HILDRETH, FL",SP,29.960278,-82.772222,S,NAD83,8.62,...,3.0,26617,NaN,wat,NaN,17164583,0,2002-02-15,2012-09-29,3659

,Unnamed: 0,OID_,Name,FolderPath,SymbolID,AltMode,Base,Snippet,HasLabel,LabelID,Active,station_nm,dec_lat_va,dec_long_va,data_start,data_end,stn_type,county
131,131,NaN,02321970,SRWMD All Monitoring Stations/SRWMD All Data C...,3,-1,0.0,NaN,-1,1,Yes,Hornsby Springs,29.850639,-82.592194,4/19/1972,CURRENT,Spring,Alachua
151,151,NaN,02322685,SRWMD All Monitoring Stations/SRWMD All Data C...,3,-1,0.0,NaN,-1,1,Yes,Ichetucknee Head Spring,30.022543,-82.777496,7/11/1975,CURRENT,Spring,Suwannee
152,152,NaN,02322688,SRWMD All Monitoring Stations/SRWMD All Data C...,3,-1,0.0,NaN,-1,1,Yes,BLUE HOLE SPRING,29.979444,-82.758611,5/17/1946,CURRENT,Spring,Columbia
154,154,NaN,02322698,SRWMD All Monitoring Stations/SRWMD All Data C...,3,-1,0.0,NaN,-1,1,No,Ichetucknee River at Dampier's Landing,29.960389,-82.771278,8/11/1993,1/1/2015,Spring,Columbia
286,286,NaN,DYE010C1,SRWMD All Monitoring Stations/SRWMD All Data C...,3,-1,0.0,NaN,-1,1,No,DEVIL EYE SANTA FE RIVER,29.835114,-82.696594,11/4/1997,11/4/1997,Spring,Gilchrist

In [92]:
id_search_results_epa = search_results_epa[['OrganizationIdentifier', 'OrganizationFormalName','MonitoringLocationIdentifier', 'MonitoringLocationName','MonitoringLocationTypeName']]
id_search_results_usgs = search_results_usgs[['site_no','station_nm','dec_lat_va','dec_long_va','site_tp_cd']]
id_search_results_srwmd = search_results_srwmd[['Name','station_nm','dec_lat_va','dec_long_va']]

id_search_results_usgs.drop_duplicates(inplace=True)

valid_epa_sites = search_results_epa.MonitoringLocationIdentifier.unique()
valid_usgs_sites = search_results_usgs.site_no.unique()
valid_srwmd_sites = search_results_srwmd.Name.unique()

<ipython-input-92-430728b0db7c>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  id_search_results_usgs.drop_duplicates(inplace=True)

In [93]:
print("EPA sites: " + str(valid_epa_sites))
print("USGS sites: "+str(valid_usgs_sites))
print("SRWMD sites: "+str(valid_srwmd_sites))

EPA sites: ['USGS-02322400' 'USGS-02322688' '21FLFSI_WQX-ICH BLUE HOLE SPRING'
 '21FLFSI_WQX-ICHETUCKNEE HEAD SPRING' '21FLGW_WQX-11407'
 '21FLGW_WQX-11418' '21FLGW_WQX-9677' '21FLGW_WQX-9681' '21FLGW_WQX-9713'
 '21FLGW_WQX-9743' '21FLSUW_WQX-GIN010C1' '21FLSUW_WQX-HOR010C1'
 '21FLSUW_WQX-ICH002C1']
USGS sites: ['02322400' '02322685' '02322688' '02322694' '02322698']
SRWMD sites: ['02321970' '02322685' '02322688' '02322698' 'DYE010C1']

In [94]:
epa_sites_retrieve = ['USGS-02322400', 'USGS-02322688', '21FLFSI_WQX-ICH BLUE HOLE SPRING',
 '21FLFSI_WQX-ICHETUCKNEE HEAD SPRING', '21FLGW_WQX-11407',
 '21FLGW_WQX-11418', '21FLGW_WQX-9677', '21FLGW_WQX-9681', '21FLGW_WQX-9713',
 '21FLGW_WQX-9743', '21FLSUW_WQX-GIN010C1', '21FLSUW_WQX-HOR010C1',
 '21FLSUW_WQX-ICH002C1']

usgs_sites_retrieve = ['02322400', '02322685', '02322688', '02322694', '02322698']

# EPA Retrieval

In [105]:
wqp_n_results_spring = pd.read_csv('C://Users/robert.taylor/Downloads//N_WQP_results_meta_spring.csv', converters={'USGSPCode': lambda x: str(x)})
epa_search_data = wqp_n_results_spring.loc[wqp_n_results_spring['MonitoringLocationIdentifier'].str.startswith(tuple(epa_sites_retrieve))]
epa_search_data = id_search_results_epa.merge(epa_search_data,on='MonitoringLocationIdentifier')
epa_search_data.to_csv('C://Users/robert.taylor/Documents/SuwData/WendyGrahamSites/EPA_NearGinnieIcheHornsby.csv')

# USGS Retrieval

In [96]:
parm_codes=pd.read_csv('C:/Users/robert.taylor/Documents/SuwData/USGS_All_Parameter_Codes.csv', converters={'parm_cd':lambda x: str(x)})
parm_codes

,Unnamed: 0,parm_cd,count_nu,grp_nm,parm_desc,CASRN,SRSName,parm_unit
0,1646,00010,118,Physical,"Temperature, water, degrees Celsius",NaN,"Temperature, water",deg C
1,1951,62611,94,Physical,"Groundwater level above NAVD 1988, feet",NaN,NaN,ft
2,2059,72019,94,Physical,"Depth to water level, feet below land surface",NaN,Depth to water level below land surface,ft
3,1950,62610,94,Physical,"Groundwater level above NGVD 1929, feet",NaN,NaN,ft
4,1692,00095,89,Physical,"Specific conductance, water, unfiltered, micro...",NaN,Specific conductance,uS/cm @25C
5,1677,00065,87,Physical,"Gage height, feet",NaN,"Height, gage",ft
6,1673,00060,67,Physical,"Discharge, cubic feet per second",NaN,"Stream flow, mean. daily",ft3/s
7,3421,99133,33,Nutrient,"Nitrate plus nitrite, water, in situ, milligra...",NaN,Inorganic nitrogen (nitrate and nitrite),mg/l as N
8,2740,00300,30,"Inorganics, Major, Non-metals","Dissolved oxygen, water, unfiltered, milligram...",7782-44-7,Oxygen,mg/l
9,1733,00400,30,Physical,"pH, water, unfiltered, field, standard units",NaN,pH,std units
10,1660,00045,26,Physical,"Precipitation, total, inches",NaN,Precipitation,in
11,1739,00480,22,Physical,"Salinity, water, unfiltered, parts per thousand",NaN,Salinity,ppth
12,2001,63160,12,Physical,"Stream water level elevation above NAVD 1988, ...",NaN,NaN,ft
13,2060,72020,10,Physical,"Elevation above NGVD 1929, feet",NaN,NaN,ft
14,2008,63680,3,Physical,"Turbidity, water, unfiltered, monochrome near ...",NaN,Turbidity,FNU
15,2112,72192,2,Physical,"Precipitation, cumulative, inches",NaN,Precipitation,in
16,19102,80155,1,Sediment,"Suspended sediment discharge, short tons per day",NaN,Suspended sediment discharge,tons/day
17,2081,72137,1,Physical,"Discharge, tidally filtered, cubic feet per se...",NaN,NaN,ft3/s
18,19101,80154,1,Sediment,"Suspended sediment concentration, milligrams p...",NaN,Suspended sediment concentration (SSC),mg/l
19,1999,63158,1,Physical,"Stream water level elevation above NGVD 1929, ...",NaN,NaN,ft

In [97]:
count = 0
usgs_dict={}
    

for i in range(len(usgs_sites_retrieve)):
    usgs_site_no = usgs_sites_retrieve[i]
    url = 'https://waterdata.usgs.gov/nwis/dv?referred_module=sw&search_site_no='+usgs_site_no+'&search_site_no_match_type=exact&site_tp_cd=SP&dv_count_nu=20&index_pmcode_00055=1&index_pmcode_00060=1&index_pmcode_00061=1&index_pmcode_00065=1&index_pmcode_30207=1&index_pmcode_30208=1&index_pmcode_30209=1&index_pmcode_62611=1&index_pmcode_62613=1&index_pmcode_00010=1&index_pmcode_00011=1&index_pmcode_00600=1&index_pmcode_00613=1&index_pmcode_00618=1&index_pmcode_00620=1&index_pmcode_00630=1&index_pmcode_00631=1&group_key=NONE&sitefile_output_format=html_table&column_name=agency_cd&column_name=site_no&column_name=station_nm&column_name=site_tp_cd&column_name=dec_lat_va&column_name=dec_long_va&column_name=qw_begin_date&column_name=qw_end_date&column_name=qw_count_nu&range_selection=date_range&begin_date=1980-01-01&end_date=2021-08-03&format=rdb&date_format=YYYY-MM-DD&rdb_compression=value&list_of_search_criteria=search_site_no%2Csite_tp_cd%2Cobs_count_nu%2Crealtime_parameter_selection'
    page = urllib.request.urlopen(url)
    skiplines = str(page.read())
    skiprow = skiplines.count('#')
    usgs_site_data = pd.read_csv(url,sep='\t',skiprows=skiprow)
    usgs_site_data.drop([0],axis=0,inplace=True)
    
            
            
    
    usgs_dict['site_no_'+str(usgs_site_no)] = usgs_site_data
    count += 1

In [98]:
usgs_dict['site_no_02322688']

,agency_cd,site_no,datetime,229570_00060_00003,229570_00060_00003_cd,26590_00065_00003,26590_00065_00003_cd,26592_00010_00001,26592_00010_00001_cd,26593_00010_00002,26593_00010_00002_cd,26594_00010_00003,26594_00010_00003_cd
1,USGS,02322688,2002-02-05,80.0,A,1.71,A,NaN,NaN,NaN,NaN,NaN,NaN
2,USGS,02322688,2002-02-06,80.5,A,1.72,A,NaN,NaN,NaN,NaN,NaN,NaN
3,USGS,02322688,2002-02-07,80.7,A,1.72,A,NaN,NaN,NaN,NaN,NaN,NaN
4,USGS,02322688,2002-02-08,79.7,A,1.70,A,NaN,NaN,NaN,NaN,NaN,NaN
5,USGS,02322688,2002-02-09,79.2,A,1.69,A,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7116,USGS,02322688,2021-07-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7117,USGS,02322688,2021-07-31,NaN,NaN,NaN,NaN,21.8,P,21.7,P,21.8,P
7118,USGS,02322688,2021-08-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7119,USGS,02322688,2021-08-02,90.6,P,2.83,P,21.8,P,21.7,P,21.8,P
7120,USGS,02322688,2021-08-03,90.9,P,2.83,P,22.7,P,21.7,P,21.8,P

In [99]:
header = usgs_dict['site_no_02322688'].columns.values.tolist()
header = pd.DataFrame(header,columns=['cols'])
header = header.cols.str.extract(r'^\w\w\w\w\w_([^_]+)_(.+)',expand=False)

display(parm_codes.loc[parm_codes['parm_cd'] == str(header.loc[3,0])]['parm_desc'])

keys = list(usgs_dict)
print(keys)

hdr = {}

for x in range(len(usgs_dict)):
    
    header = usgs_dict[keys[x]].columns.values.tolist()
    header = pd.DataFrame(header,columns=['cols'])
    header = header.cols.str.extract(r'^\w{3,8}_([^_]+)_(.+)',expand=False)
    
    for i in range(header.shape[0]):
        for j in range(header.shape[1]):
            if header.iloc[i,j] == '00001':
                header.iloc[i,j] = 'Max value'
            elif header.iloc[i,j] == '00002':
                header.iloc[i,j] = 'Min value'
            elif header.iloc[i,j] == '00003':
                header.iloc[i,j] = 'Mean value'
            elif header.iloc[i,j] == '00001_cd':
                header.iloc[i,j] = 'Data status / quality'
            elif header.iloc[i,j] == '00002_cd':
                header.iloc[i,j] = 'Data status / quality'
            elif header.iloc[i,j] == '00003_cd':
                header.iloc[i,j] = 'Data status / quality'
            elif pd.isna(header.iloc[i,j]) is False:
                header.iloc[i,j] = parm_codes.loc[parm_codes['parm_cd'] == str(header.iloc[i,j])]['parm_desc'].values
    
    hdr[keys[x]] = header

Series([], Name: parm_desc, dtype: object)

['site_no_02322400', 'site_no_02322685', 'site_no_02322688', 'site_no_02322694', 'site_no_02322698']

In [100]:
header = usgs_dict['site_no_02322688'].columns.values.tolist()
header = pd.DataFrame(header,columns=['cols'])
header = header.cols.str.extract(r'^\w\w\w\w\w_([^_]+)_(.+)',expand=False)


keys = list(usgs_dict)
print(keys)

hdr = {}

for x in range(len(usgs_dict)):
    
    header = usgs_dict[keys[x]].columns.values.tolist()
    header = pd.DataFrame(header,columns=['cols'])
    header = header.cols.str.extract(r'^\w{3,8}_([^_]+)_(.+)',expand=False)
    
    for i in range(header.shape[0]):
        for j in range(header.shape[1]):
            if header.iloc[i,j] == '00001':
                header.iloc[i,j] = ', Max value'
            elif header.iloc[i,j] == '00002':
                header.iloc[i,j] = ', Min value'
            elif header.iloc[i,j] == '00003':
                header.iloc[i,j] = ', Mean value'
            elif header.iloc[i,j] == '00001_cd':
                header.iloc[i,j] = ' Data status / quality'
            elif header.iloc[i,j] == '00002_cd':
                header.iloc[i,j] = ' Data status / quality'
            elif header.iloc[i,j] == '00003_cd':
                header.iloc[i,j] = ' Data status / quality'
            elif pd.isna(header.iloc[i,j]) is False:
                header.iloc[i,j] = parm_codes.loc[parm_codes['parm_cd'] == str(header.iloc[i,j])]['parm_desc'].values
    
    hdr[keys[x]] = header
        
display(hdr[keys[3]].iloc[3,1])

for i in range(len(usgs_dict)):
    hdr[keys[i]]['header'] = hdr[keys[i]][0].astype(str) + hdr[keys[i]][1].astype(str)
    hdr[keys[i]] = hdr[keys[i]]['header']
    hdr[keys[i]].iloc[0] = 'agency_cd'
    hdr[keys[i]].iloc[1] = 'site_no'
    hdr[keys[i]].iloc[2] = 'datetime'
    

#display(hdr[keys[0]].values.tolist())



header_usgs = {}



for i in range(len(usgs_dict)):
    header_usgs[keys[i]] = usgs_dict[keys[i]].columns.values.tolist()
    usgs_dict[keys[i]].columns = hdr[keys[i]].values

['site_no_02322400', 'site_no_02322685', 'site_no_02322688', 'site_no_02322694', 'site_no_02322698']

', Mean value'

In [101]:
display(usgs_dict[keys[0]])
display(hdr[keys[0]])

,agency_cd,site_no,datetime,"['Gage height, feet'], Mean value","['Gage height, feet'] Data status / quality","['Temperature, water, degrees Celsius'], Min value","['Temperature, water, degrees Celsius'] Data status / quality","['Temperature, water, degrees Celsius'], Max value","['Temperature, water, degrees Celsius'] Data status / quality"
1,USGS,02322400,2018-11-09,22.17,A,NaN,NaN,NaN,NaN
2,USGS,02322400,2018-11-10,22.15,A,NaN,NaN,NaN,NaN
3,USGS,02322400,2018-11-11,22.13,A,NaN,NaN,NaN,NaN
4,USGS,02322400,2018-11-12,22.16,A,NaN,NaN,NaN,NaN
5,USGS,02322400,2018-11-13,22.18,A,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
968,USGS,02322400,2021-07-03,24.85,P,22.6,P,22.7,P
969,USGS,02322400,2021-07-04,NaN,NaN,NaN,NaN,NaN,NaN
970,USGS,02322400,2021-07-05,NaN,NaN,NaN,NaN,NaN,NaN
971,USGS,02322400,2021-07-06,NaN,NaN,NaN,NaN,NaN,NaN
972,USGS,02322400,2021-07-07,24.75,P,22.6,P,22.7,P

0                                            agency_cd
1                                              site_no
2                                             datetime
3                    ['Gage height, feet'], Mean value
4          ['Gage height, feet'] Data status / quality
5    ['Temperature, water, degrees Celsius'], Min v...
6    ['Temperature, water, degrees Celsius'] Data s...
7    ['Temperature, water, degrees Celsius'], Max v...
8    ['Temperature, water, degrees Celsius'] Data s...
Name: header, dtype: object

In [102]:
for i in range(len(usgs_dict)):
    usgs_dict[keys[i]] = id_search_results_usgs.merge(usgs_dict[keys[i]],on='site_no')
    #usgs_dict[keys[i]] = usgs_dict[keys[i]].merge(id_search_results_usgs,on='site_no')
    usgs_dict[keys[i]].to_csv('C:/Users/robert.taylor/Documents/SuwData/WendyGrahamSites/USGS_'+keys[i]+'_data.csv')